# Generated by Django 5.2.6 on 2025-09-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('total_bottles_processed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('bottle_detected', 'Bottle Detected'), ('bottle_sorted', 'Bottle Sorted'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('heartbeat', 'Heartbeat')], max_length=20)),
                ('sort_result', models.CharField(blank=True, choices=[('plastic', 'Plastic (Valid)'), ('invalid', 'Invalid (Not Plastic)'), ('error', 'Error')], max_length=10, null=True)),
                ('sensor_data', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
    ]
