# Generated by Django 5.0.6 on 2025-10-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student: C22-0369 | Faculty: SMCIC-001-0001 | Editable', max_length=50, null=True, unique=True),
        ),
    ]
