# Generated by Django 5.0.6 on 2025-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rewards/'),
        ),
    ]
