# Generated by Django 5.0.6 on 2025-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rewarditem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewarditem',
            name='icon',
        ),
    ]
