# Generated by Django 5.0.6 on 2025-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_id',
            field=models.CharField(blank=True, help_text='School ID (Students: C22-0369 | Faculty: SMCIC-001-0001)', max_length=50, null=True, unique=True, verbose_name='School ID Number'),
        ),
    ]
