# Generated by Django 5.0.6 on 2025-12-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedpoints',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
